**QUESTION 1: Upload dataset and define dependent variable**

In [37]:
import pandas as pd

df = pd.read_csv("WHO_Covid_19_Jan22_2021.csv", encoding="latin1")

df.head()

,Name,WHO Region,Cases _cumulative total,Cases _cumulative total per 1 million population,Cases _newly reported in last 7 days,Cases _newly reported in last 24 hours,Deaths _cumulative total,Deaths_ cumulative total per 1 million population,Deaths _newly reported in last 7 days,Deaths _newly reported in last 24 hours,Transmission Classification
0,South Africa,Africa,1369426,23089.80,91123,12710,38854,655.11,3714,566,Community transmission
1,Ethiopia,Africa,132034,1148.49,2589,307,2044,17.78,38,7,Community transmission
2,Nigeria,Africa,114691,556.38,10692,1386,1478,7.17,96,14,Community transmission
3,Algeria,Africa,104606,2385.48,1965,265,2854,65.08,38,6,Community transmission
4,Kenya,Africa,99444,1849.39,889,136,1736,32.28,16,2,Community transmission

In [38]:
df.columns

Index(['Name', 'WHO Region', 'Cases _cumulative total',
       'Cases _cumulative total per 1 million population',
       'Cases _newly reported in last 7 days',
       'Cases _newly reported in last 24 hours', 'Deaths _cumulative total',
       'Deaths_ cumulative total per 1 million population',
       'Deaths _newly reported in last 7 days',
       'Deaths _newly reported in last 24 hours',
       'Transmission Classification'],
      dtype='object')

In [39]:
X = df.drop("Transmission Classification", axis=1)
y = df["Transmission Classification"]

print("Independent variables shape:", X.shape)
print("Dependent variable shape:", y.shape)

Independent variables shape: (238, 10)
Dependent variable shape: (238,)

The dataset was successfully uploaded into the Google Colab environment using the pandas library. The dependent variable selected for prediction was Transmission Classification, while the remaining variables were treated as independent variables. The dataset structure was verified by displaying the column names and confirming the feature and target variable dimensions.

**QUESTION 2: Use appropriate data mining methodologies and clean the dataset downloaded**

In [40]:
df = df.drop("Name", axis=1)

df.head()

,WHO Region,Cases _cumulative total,Cases _cumulative total per 1 million population,Cases _newly reported in last 7 days,Cases _newly reported in last 24 hours,Deaths _cumulative total,Deaths_ cumulative total per 1 million population,Deaths _newly reported in last 7 days,Deaths _newly reported in last 24 hours,Transmission Classification
0,Africa,1369426,23089.80,91123,12710,38854,655.11,3714,566,Community transmission
1,Africa,132034,1148.49,2589,307,2044,17.78,38,7,Community transmission
2,Africa,114691,556.38,10692,1386,1478,7.17,96,14,Community transmission
3,Africa,104606,2385.48,1965,265,2854,65.08,38,6,Community transmission
4,Africa,99444,1849.39,889,136,1736,32.28,16,2,Community transmission

The column Name was removed from the dataset because it represents country names, which do not contribute to predicting transmission classification. Removing irrelevant attributes improves model performance and reduces unnecessary complexity.

In [41]:
df.isnull().sum()

WHO Region                                           1
Cases _cumulative total                              0
Cases _cumulative total per 1 million population     1
Cases _newly reported in last 7 days                 0
Cases _newly reported in last 24 hours               0
Deaths _cumulative total                             0
Deaths_ cumulative total per 1 million population    1
Deaths _newly reported in last 7 days                0
Deaths _newly reported in last 24 hours              0
Transmission Classification                          1
dtype: int64

In [42]:
df = df.dropna()

df.isnull().sum()

WHO Region                                           0
Cases _cumulative total                              0
Cases _cumulative total per 1 million population     0
Cases _newly reported in last 7 days                 0
Cases _newly reported in last 24 hours               0
Deaths _cumulative total                             0
Deaths_ cumulative total per 1 million population    0
Deaths _newly reported in last 7 days                0
Deaths _newly reported in last 24 hours              0
Transmission Classification                          0
dtype: int64

Missing values were identified in several variables within the dataset. These missing observations were removed using the dropna() function to ensure compatibility with machine learning classifiers such as K-Nearest Neighbour and Support Vector Machine, which do not support missing values directly. This step improved the reliability of the dataset before model training.

In [43]:
from sklearn.preprocessing import LabelEncoder

le_region = LabelEncoder()
le_target = LabelEncoder()

df["WHO Region"] = le_region.fit_transform(df["WHO Region"])
df["Transmission Classification"] = le_target.fit_transform(df["Transmission Classification"])

df.head()

,WHO Region,Cases _cumulative total,Cases _cumulative total per 1 million population,Cases _newly reported in last 7 days,Cases _newly reported in last 24 hours,Deaths _cumulative total,Deaths_ cumulative total per 1 million population,Deaths _newly reported in last 7 days,Deaths _newly reported in last 24 hours,Transmission Classification
0,0,1369426,23089.80,91123,12710,38854,655.11,3714,566,1
1,0,132034,1148.49,2589,307,2044,17.78,38,7,1
2,0,114691,556.38,10692,1386,1478,7.17,96,14,1
3,0,104606,2385.48,1965,265,2854,65.08,38,6,1
4,0,99444,1849.39,889,136,1736,32.28,16,2,1

Categorical variables such as WHO Region and Transmission Classification were converted into numerical format using Label Encoding. Machine learning algorithms require numerical input values for training classification models, therefore encoding categorical variables improves compatibility with classification techniques.

In [44]:
X = df.drop("Transmission Classification", axis=1)
y = df["Transmission Classification"]

print("Features shape:", X.shape)
print("Target shape:", y.shape)

Features shape: (236, 9)
Target shape: (236,)

In [45]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_scaled = scaler.fit_transform(X)

X_scaled[:5]

array([[-1.26772828,  0.51770162,  0.21708248,  0.75360055,  0.73213444,
         0.86946007,  0.83192078,  1.91935195,  1.42796145],
       [-1.26772828, -0.14779077, -0.74544166, -0.16900758, -0.18116441,
        -0.19530903, -0.68133295, -0.21025396, -0.18721081],
       [-1.26772828, -0.15711816, -0.77141642, -0.08456665, -0.1017119 ,
        -0.2116812 , -0.70652496, -0.17665299, -0.16698504],
       [-1.26772828, -0.16254206, -0.69117723, -0.17551025, -0.18425709,
        -0.17187891, -0.56902551, -0.21025396, -0.19010021],
       [-1.26772828, -0.16531828, -0.71469449, -0.18672319, -0.19375605,
        -0.20421827, -0.64690466, -0.22299915, -0.20165779]])

Feature scaling was performed using the StandardScaler technique to standardize the dataset variables. This step ensures that all features contribute equally during model training, especially for distance-based classifiers such as K-Nearest Neighbour and Support Vector Machine.

In [46]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X_scaled,
    y,
    test_size=0.3,
    random_state=42
)

print("Training set size:", X_train.shape)
print("Testing set size:", X_test.shape)

Training set size: (165, 9)
Testing set size: (71, 9)

The dataset was divided into training and testing subsets using the train_test_split function. Seventy percent (70%) of the dataset was used for training the models, while thirty percent (30%) was reserved for testing model performance. This ensures reliable evaluation of classifier accuracy.

QUESTION 3: Use Decision Trees, Random Forest, K-Nearest Neighbour and Support Vector Machine classifiers to predict different Transmission Classification of the pandemic by determining the performance metrics such as precision, recall, F1-score, accuracy and Jaccard index.

In [48]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report, accuracy_score, jaccard_score

dt_model = DecisionTreeClassifier(random_state=42)

dt_model.fit(X_train, y_train)

dt_predictions = dt_model.predict(X_test)

print(classification_report(y_test, dt_predictions))
print("Accuracy:", accuracy_score(y_test, dt_predictions))
print("Jaccard Index:", jaccard_score(y_test, dt_predictions, average='weighted'))

              precision    recall  f1-score   support

           0       0.07      0.08      0.07        13
           1       0.72      0.63      0.68        41
           2       0.89      0.80      0.84        10
           3       0.00      0.00      0.00         0
           4       0.40      0.57      0.47         7

    accuracy                           0.55        71
   macro avg       0.42      0.42      0.41        71
weighted avg       0.59      0.55      0.57        71

Accuracy: 0.5492957746478874
Jaccard Index: 0.4342047071955936

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

The Decision Tree classifier was applied to predict transmission classification using the cleaned dataset. The model performance was evaluated using precision, recall, F1-score, accuracy and Jaccard similarity index. The results show that the Decision Tree classifier achieved moderate classification performance, demonstrating its ability to identify transmission classification patterns within the dataset. However, Decision Trees may experience some misclassification due to their sensitivity to dataset variations compared to ensemble learning techniques.

In [49]:
from sklearn.metrics import confusion_matrix

confusion_matrix(y_test, dt_predictions)

array([[ 1,  8,  0,  2,  2],
       [13, 26,  0,  0,  2],
       [ 0,  0,  8,  0,  2],
       [ 0,  0,  0,  0,  0],
       [ 0,  2,  1,  0,  4]])

The confusion matrix illustrates the classification performance of the Decision Tree model by comparing predicted transmission classifications with the actual values. The diagonal elements represent correctly classified observations, while off-diagonal values indicate misclassifications between transmission categories.

In [50]:
from sklearn.ensemble import RandomForestClassifier

rf_model = RandomForestClassifier(random_state=42)

rf_model.fit(X_train, y_train)

rf_predictions = rf_model.predict(X_test)

print(classification_report(y_test, rf_predictions))
print("Accuracy:", accuracy_score(y_test, rf_predictions))
print("Jaccard Index:", jaccard_score(y_test, rf_predictions, average='weighted'))

              precision    recall  f1-score   support

           0       0.29      0.15      0.20        13
           1       0.80      0.85      0.82        41
           2       0.82      0.90      0.86        10
           4       0.33      0.43      0.38         7

    accuracy                           0.69        71
   macro avg       0.56      0.58      0.56        71
weighted avg       0.66      0.69      0.67        71

Accuracy: 0.6901408450704225
Jaccard Index: 0.5529553388708318

The Random Forest classifier was applied to improve prediction accuracy by combining multiple decision trees through an ensemble learning approach. The performance metrics obtained, including precision, recall, F1-score, accuracy and Jaccard similarity index, indicate improved classification performance compared to the Decision Tree model. Random Forest reduces overfitting and increases prediction reliability by aggregating results from multiple trees.

In [51]:
confusion_matrix(y_test, rf_predictions)

array([[ 2,  7,  0,  4],
       [ 5, 35,  0,  1],
       [ 0,  0,  9,  1],
       [ 0,  2,  2,  3]])

The confusion matrix for the Random Forest classifier shows the number of correct and incorrect predictions made by the model across the different transmission classification categories. Higher values along the diagonal indicate stronger classification accuracy compared to the Decision Tree model.

In [52]:
from sklearn.neighbors import KNeighborsClassifier

knn_model = KNeighborsClassifier(n_neighbors=5)

knn_model.fit(X_train, y_train)

knn_predictions = knn_model.predict(X_test)

print(classification_report(y_test, knn_predictions))
print("Accuracy:", accuracy_score(y_test, knn_predictions))
print("Jaccard Index:", jaccard_score(y_test, knn_predictions, average='weighted'))

              precision    recall  f1-score   support

           0       0.24      0.31      0.27        13
           1       0.75      0.73      0.74        41
           2       0.89      0.80      0.84        10
           4       0.40      0.29      0.33         7

    accuracy                           0.62        71
   macro avg       0.57      0.53      0.55        71
weighted avg       0.64      0.62      0.63        71

Accuracy: 0.6197183098591549
Jaccard Index: 0.4900052722753634

The K-Nearest Neighbour classifier was applied to predict transmission classification using distance-based similarity between observations. The model performance was evaluated using precision, recall, F1-score, accuracy and Jaccard similarity index. The results indicate moderate classification performance. Since KNN relies on similarity between neighbouring data points, its performance depends on dataset structure and feature scaling.

In [53]:
confusion_matrix(y_test, knn_predictions)

array([[ 4,  7,  0,  2],
       [10, 30,  0,  1],
       [ 1,  1,  8,  0],
       [ 2,  2,  1,  2]])

The confusion matrix for the K-Nearest Neighbour classifier shows the distribution of correct and incorrect predictions across the transmission classification categories. The diagonal elements represent correctly classified observations, while off-diagonal elements indicate classification errors between categories.

In [54]:
from sklearn.svm import SVC

svm_model = SVC()

svm_model.fit(X_train, y_train)

svm_predictions = svm_model.predict(X_test)

print(classification_report(y_test, svm_predictions))
print("Accuracy:", accuracy_score(y_test, svm_predictions))
print("Jaccard Index:", jaccard_score(y_test, svm_predictions, average='weighted'))

              precision    recall  f1-score   support

           0       0.20      0.31      0.24        13
           1       0.75      0.93      0.83        41
           2       0.00      0.00      0.00        10
           4       0.00      0.00      0.00         7

    accuracy                           0.59        71
   macro avg       0.24      0.31      0.27        71
weighted avg       0.47      0.59      0.52        71

Accuracy: 0.5915492957746479
Jaccard Index: 0.43161908873419313

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

The Support Vector Machine classifier was applied to predict transmission classification by identifying optimal decision boundaries between classes. The model performance was evaluated using precision, recall, F1-score, accuracy and Jaccard similarity index. The results indicate moderate classification performance. Support Vector Machine classifiers perform well when classes are clearly separable, but performance may reduce when there is overlap between transmission classification categories.

In [55]:
confusion_matrix(y_test, svm_predictions)

array([[ 4,  9,  0,  0],
       [ 3, 38,  0,  0],
       [ 9,  1,  0,  0],
       [ 4,  3,  0,  0]])

The confusion matrix for the Support Vector Machine classifier shows the number of correctly and incorrectly predicted transmission classification categories. The diagonal values represent correct classifications, while off-diagonal values indicate misclassification between categories.

QUESTION 4: Produce the confusion matrix for the classifier where necessary

In [56]:
confusion_matrix(y_test, rf_predictions)

array([[ 2,  7,  0,  4],
       [ 5, 35,  0,  1],
       [ 0,  0,  9,  1],
       [ 0,  2,  2,  3]])

The confusion matrix above represents the classification performance of the Random Forest model, which achieved the highest accuracy among all classifiers used in this experiment. The diagonal elements indicate correctly predicted transmission classifications, while off-diagonal elements represent misclassifications between categories. This confirms that the Random Forest classifier produced the most reliable predictions compared to the other models.

**QUESTION 5: What is your conclusion of the experiment and why?**

In this experiment, four classification algorithms were applied to predict COVID-19 transmission classification using the WHO dataset. These included Decision Tree, Random Forest, K-Nearest Neighbour and Support Vector Machine classifiers. The performance of each classifier was evaluated using precision, recall, F1-score, accuracy and Jaccard similarity index.

Among the four classifiers, the Random Forest model achieved the highest classification accuracy and Jaccard similarity index compared to the other models. This indicates stronger agreement between predicted and actual transmission classification categories. The improved performance of the Random Forest classifier is attributed to its ensemble learning approach, which combines multiple decision trees and reduces overfitting while improving prediction reliability.

Therefore, Random Forest was identified as the most suitable classifier for predicting transmission classification in this dataset.

**MODEL PERFORMANCE COMPARISON SUMMARY**

The table below summarizes the performance of the four classification algorithms used in this experiment. The comparison is based on classification accuracy and Jaccard similarity index, which were used to determine the most suitable model for predicting COVID-19 transmission classification.

In [57]:
import pandas as pd
from sklearn.metrics import accuracy_score, jaccard_score

comparison_table = pd.DataFrame({
    "Model": [
        "Decision Tree",
        "Random Forest",
        "K-Nearest Neighbour",
        "Support Vector Machine"
    ],
    "Accuracy": [
        accuracy_score(y_test, dt_predictions),
        accuracy_score(y_test, rf_predictions),
        accuracy_score(y_test, knn_predictions),
        accuracy_score(y_test, svm_predictions)
    ],
    "Jaccard Index": [
        jaccard_score(y_test, dt_predictions, average='weighted'),
        jaccard_score(y_test, rf_predictions, average='weighted'),
        jaccard_score(y_test, knn_predictions, average='weighted'),
        jaccard_score(y_test, svm_predictions, average='weighted')
    ]
})

comparison_table

                    Model  Accuracy  Jaccard Index
0           Decision Tree  0.549296       0.434205
1           Random Forest  0.690141       0.552955
2     K-Nearest Neighbour  0.619718       0.490005
3  Support Vector Machine  0.591549       0.431619

The comparison table above shows the performance of the four classification algorithms used in this study. Based on the evaluation metrics, the Random Forest classifier achieved the highest accuracy and Jaccard similarity index among the models tested. This confirms that Random Forest produced the most reliable predictions for transmission classification compared to Decision Tree, K-Nearest Neighbour and Support Vector Machine classifiers.